export const home: string;
export const heroImage: string;
export const content: string;
export const section: string;
export const section2: string;
export const contentBlock: string;
export const section3: string;
export const quote: string;
export const methods: string;
