backend:
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Hero Image"
            name: "hero"
            widget: "image"
            default: "src/static/img/hero.jpg"
            media_library:
              config:
                multiple: true
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Methods"
            name: "methods"
            widget: list
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }