backend:
  name: git-gateway
  branch: master
media_folder: "src/static/img"
public_folder: "/static/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/home.md"
        fields:
          - label: "Hero Image"
            name: "hero"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Section 1"
            name: "section1"
            widget: "object"
            fields:
              - { label: "Quote", name: "quote", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "string" }
          - label: "Section 2"
            name: "section2"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "string" }
          - label: "Methods"
            name: "methods"
            widget: list
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }