backend:
  name: test-repo
  branch: master

media_folder: "src/static/img"
public_folder: "/static/img"

collections:
  - name: "pages"
    label: "Pages"
    files:

      - label: "Home"
        name: "home"
        file: "src/content/home.md"
        fields:
          - label: "Hero Image"
            name: "hero"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Section 1"
            name: "section1"
            widget: "object"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }
          - label: "Section 2"
            name: "section2"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }
          - label: "Section 3"
            name: "section3"
            widget: "object"
            fields:
              - label: "Background Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }
          - label: "Section 4"
            name: "section4"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }
          - label: "Methods"
            name: "methods"
            widget: list
            fields: 
              - label: "Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }
          - label: "Section 5"
            name: "section5"
            widget: "object"
            fields:
              - label: "Background Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
          - label: "About Me"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Image"
                name: "image"
                widget: "image"
                default: "src/static/img/hero.jpg"
                media_library:
                  config:
                    multiple: true
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "More Link", name: "link", widget: "relation", collection: "blog", searchFields: ["name"], valueField: "name" }

  - label: "Blog"
    name: "blog"
    identifier_field: "name"
    folder: "src/content/blog"
    create: true
    fields: 
      - { label: "Name", name: "name", widget: "string", pattern: ['^[a-z-]+$', 'Only use lowercase and "-" for spaces'] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Intro Text", name: "intro", widget: "text" }
      - label: "Image"
        name: "image"
        widget: "image"
        default: "src/static/img/hero.jpg"
        media_library:
          config:
            multiple: true
      - label: "Content"
        name: "content"
        widget: "list"
        types:
          - label: "Text"
            name: "text"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "markdown" }
          - label: "Quote"
            name: "quote"
            widget: "object"
            fields: 
              - { label: "Quote", name: "quote", widget: "text"}
              - { label: "Author", name: "author", widget: "string" }