backend:
  name: git-gateway
  branch: master
media_folder: src/static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Methods"
            name: "methods"
            widget: list
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }